#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# tmux
mkdir -p $HOME/.local/bin
ln -sf $DOTFILES/tmux/t $HOME/.local/bin/t

rm -rf $HOME/.tmux.conf
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# nvim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# lua
rm -rf $HOME/.luacheckrc
ln -s $DOTFILES/lua/luacheckrc $HOME/.luacheckrc
